apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name | default "nikke-hub-secrets" }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.data.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.data.postgresPassword | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.data.springDatasourceUsername | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.data.springDatasourcePassword | b64enc | quote }}
  SPRING_FLYWAY_USER: {{ .Values.secrets.data.springFlywayUser | b64enc | quote }}
  SPRING_FLYWAY_PASSWORD: {{ .Values.secrets.data.springFlywayPassword | b64enc | quote }}