services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/outpost
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    depends_on:
      - db
    volumes:
      - ./build/libs/nikkeManager-0.0.1-SNAPSHOT.jar:/app/app.jar

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: outpost
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d outpost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: