apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name | default "postgres-init" }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
data:
  init.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
      CREATE DATABASE {{ .Values.configMap.databaseName }};
    EOSQL