apiVersion: v1
kind: ConfigMap
metadata:
  name: nikke-hub-backend-config
data:
  SPRING_APPLICATION_NAME: "nikke-hub-backend"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server-service:8761/eureka/"
  EUREKA_INSTANCE_PREFERIPADDRESS: "true"
  SPRING_REDIS_HOST: "redis-service"
  SPRING_REDIS_PORT: "6379"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/outpost"
  POSTGRES_DB: "outpost"