apiVersion: apps/v1
kind: Deployment
metadata:
  name: nikke-hub-backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nikke-hub-backend

  template:
    metadata:
      labels:
        app: nikke-hub-backend

    spec:
      containers:
        - name: nikke-hub-backend
          image: hyuse98/nikke-hub-backend:latest
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: nikke-hub-backend-config
            - secretRef:
                name: secrets

          ports:
            - containerPort: 8081

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10