apiVersion: v1
kind: ConfigMap
metadata:
  name: nikke-hub-config-server-config
  namespace: nikke-hub
  labels:
    app: nikke-hub

data:

  # Server Configuration
  BACKEND_SERVER_PORT: "8888"

  # Eureka Configuration
  EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: "http://nikke-hub-eureka-server-service:8761/eureka/"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_FETCH_REGISTRY: "true"

  #Config Configuration
  CONFIG_SERVER_GIT_URI: "https://github.com/Hyuse98/Config-Repo.git"
  CLONE_ON_START: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: nikke-hub-config-server-service
  namespace: nikke-hub
  labels:
    app: nikke-hub

spec:
  type: ClusterIP
  selector:
    app: nikke-hub-config-server
  ports:
  - port: 8888
    targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nikke-hub-config-server
  namespace: nikke-hub
  labels:
    app: nikke-hub
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nikke-hub-config-server

  template:
    metadata:
      labels:
        app: nikke-hub-config-server

    spec:
      containers:
      - name: nikke-hub-config-server
        image: hyuse98/nikke-hub-config-server:latest        
        imagePullPolicy: Always #IfNotPresent

        envFrom:
            - configMapRef:
                name: nikke-hub-config-server-config

        ports:
        - containerPort: 8888

        resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"