apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
      CREATE DATABASE outpost;
    EOSQL