namespace: "nikke-hub"

labels:
  app: "nikke-hub-gateway"

configMap:
  name: "gateway-config"
  data:
    GATEWAY_SERVER_PORT: "8000"

    URI_BACKEND_SERVICE: "http://nikke-hub-backend-service.nikke-hub.svc.cluster.local:8082"
    URI_EUREKA_SERVICE: "http://nikke-hub-eureka-server-service.nikke-hub.svc.cluster.local:8761"
    URI_CONFIG_SERVICE: "http://nikke-hub-config-server-service.nikke-hub.svc.cluster.local:8888"
    URI_GRAFANA: "http://grafana-service.nikke-hub.svc.cluster.local:3000"
    URI_ZIPKIN: "http://zipkin-service.nikke-hub.svc.cluster.local:9411"
    URI_PROMETHEUS: "http://prometheus-service.nikke-hub.svc.cluster.local:9090"

    EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: "http://nikke-hub-eureka-server-service:8761/eureka/"
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
    EUREKA_CLIENT_FETCH_REGISTRY: "true"

    SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: "true"

service:
  name: "gateway-service"
  port: 8000
  type: ClusterIP

deployment:
  name: "nikke-hub-gateway"
  replicas: 1
  image: "hyuse98/nikke-hub-gateway"
  tag: "latest"
  pullPolicy: Always
  port: 8000

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"
