apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
data:
  prometheus.yml: |
    {{- .Values.configMap.config | nindent 4 }}