CREATE TABLE public.doll (
	id int4 GENERATED BY DEFAULT AS IDENTITY( MINVALUE 0 NO MAXVALUE START 0 NO CYCLE) NOT NULL,
	"level" int4 NULL,
	rarity varchar(255) NULL,
	CONSTRAINT doll_pkey PRIMARY KEY (id),
	CONSTRAINT doll_rarity_check CHECK ((((rarity)::text = ANY ((ARRAY['R'::character varying, 'SR'::character varying, 'SSR'::character varying])::text[]))))
);

CREATE TABLE public.nikke (
	id int4 NOT NULL,
	attraction int4 NOT NULL,
	burst_level int4 NOT NULL,
	burst_type varchar(255) NULL,
	code varchar(255) NULL,
	company varchar(255) NULL,
	core int4 NOT NULL,
	"cube" varchar(255) NULL,
	"name" varchar(255) NULL,
	nikke_class varchar(255) NULL,
	owned_status varchar(255) NULL,
	rarity varchar(255) NULL,
	skill1level int4 NOT NULL,
	skill2level int4 NOT NULL,
	weapon varchar(255) NULL,
	doll_id int4 NULL,
	CONSTRAINT nikke_burst_type_check CHECK (((burst_type)::text = ANY ((ARRAY['I'::character varying, 'II'::character varying, 'III'::character varying, 'ALL'::character varying])::text[]))),
	CONSTRAINT nikke_code_check CHECK (((code)::text = ANY ((ARRAY['FIRE'::character varying, 'WATER'::character varying, 'WIND'::character varying, 'ELECTRIC'::character varying, 'IRON'::character varying])::text[]))),
	CONSTRAINT nikke_company_check CHECK (((company)::text = ANY ((ARRAY['ELYSION'::character varying, 'MISSILIS'::character varying, 'TETRA'::character varying, 'PILGRIM'::character varying, 'ABNORMAL'::character varying, 'ELYSION_OVERSPEC'::character varying])::text[]))),
	CONSTRAINT nikke_cube_check CHECK (((cube)::text = ANY ((ARRAY['ASSAULT'::character varying, 'ONSLAUGHT'::character varying, 'RESILIENCE'::character varying, 'BASTION'::character varying, 'ADJUTANT'::character varying, 'WINGMAN'::character varying, 'QUANTUM'::character varying, 'VIGOR'::character varying, 'ENDURANCE'::character varying, 'HEALING'::character varying, 'TEMPERING'::character varying])::text[]))),
	CONSTRAINT nikke_nikke_class_check CHECK (((nikke_class)::text = ANY ((ARRAY['ATTACKER'::character varying, 'DEFENDER'::character varying, 'SUPPORTER'::character varying])::text[]))),
	CONSTRAINT nikke_owned_status_check CHECK (((owned_status)::text = ANY ((ARRAY['OWNED'::character varying, 'NOT_OWNED'::character varying])::text[]))),
	CONSTRAINT nikke_pkey PRIMARY KEY (id),
	CONSTRAINT nikke_rarity_check CHECK (((rarity)::text = ANY ((ARRAY['R'::character varying, 'SR'::character varying, 'SSR'::character varying])::text[]))),
	CONSTRAINT nikke_weapon_check CHECK (((weapon)::text = ANY ((ARRAY['AR'::character varying, 'SMG'::character varying, 'SG'::character varying, 'SR'::character varying, 'RL'::character varying, 'MG'::character varying])::text[])))
);